version: "3.9"
services:

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    deploy:
      restart_policy:
        condition: on-failure

  db:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=benderisgreat
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: