version: "3.7"
services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:13.4-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bender
      - POSTGRES_PASSWORD=benderisgreat
      - POSTGRES_DB=planetexpress
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d