name: Deps check
on:
  pull_request:
    branches:
      - main
jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: deps
        run: make deps
      # Should not detect any differences with VCS code
      - name: diff
        run: git diff -u --color=always --exit-code
