name: Geneate
on:
  pull_request:
    branches:
      - main
jobs:
  code-gen:
    name: code-gen
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - uses: actions/checkout@v2
      - name: generate
        run: make generate
      - name: diff
        run: git diff -u --color=always --exit-code
